[package]
name = "chip8"
version = "0.1.0"
authors = ["Wojciech Bogócki <wojciechbogocki@fastmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fermium = "200.12.2"